package solutions;

/**
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 * */
public class Difference {
    public char findTheDifference(String s, String t) {
        // frequency of all ASCII characters
        int[] alphabetS = new int[256];
        int[] alphabetT = new int[256];
        char c = 0; // null

        for (int i = 0; i < s.length(); ++i) {
            ++alphabetS[s.charAt(i)];
            ++alphabetT[t.charAt(i)];
        }
        //add the last character in t
        ++alphabetT[t.charAt(t.length() - 1)];

        for (int i = 0; i < alphabetS.length; ++i) {
            if (alphabetS[i] != alphabetT[i]) {
                c =  (char)i;
            }
        }
        return c;
    }
}
